export const ChaatsData = [
    {
        id: 1,
        name: "Bread Omelette",
        image: "/images/Bakery/Chaat/Others/Bread-Omelette.jpg",
        desc:"Available with or without cheese",
        number: 9043246178,
    },
    {
        id: 2,
        name: "Panner Burger",
        image: "/images/Bakery/Chaat/Others/Panner.jpg",
        desc:"Veg Panner also Available",
        number: 9043246178,
    },
    {
        id: 3,
        name: "Masala Pav",
        image: "/images/Bakery/Chaat/Others/MasalaPav.jpg",
        number: 9043246178,
    },
    {
        id: 4,
        name: "Panner 65",
        image: "/images/Bakery/Chaat/Others/Panner 65.jpg",
        number: 9043246178,
    },
    {
        id: 5,
        name: "Potato Roll",
        image: "/images/Bakery/Chaat/Others/Potato.jpg",
        number: 9043246178,
    },
    {
        id: 6,
        name: "French Fry",
        image: "/images/Bakery/Chaat/Others/French.jpg",
        number: 9043246178,
    },
    {
        id: 7,
        name: "Chana Samosa",
        image: "/images/Bakery/Chaat/Others/ChannaSamosa.jpg",
        number: 9043246178,
    },
    {
        id: 8,
        name: "Bread Chana",
        image: "/images/Bakery/Chaat/Others/BreadChanna.jpg",
        number: 9043246178,
    },
    {
        id: 9,
        name: "Chana Masala",
        image: "/images/Bakery/Chaat/Others/ChannaMasala.jpg",
        number: 9043246178,
    },
    {
        id: 10,
        name: "Dahi Papdi",
        image: "/images/Bakery/Chaat/Others/DahiPapdi.jpg",
        number: 9043246178,
    },
    {
        id: 11,
        name: "Dahi Samosa",
        image: "/images/Bakery/Chaat/Others/DahiSamosa.jpg",
        number: 9043246178,
    },
    {
        id: 12,
        name: "Mix Chaat",
        image: "/images/Bakery/Chaat/Others/MixChaat.jpg",
        number: 9043246178,
    },
    {
        id: 13,
        name: "Samosa Chaat",
        image: "/images/Bakery/Chaat/Others/SamosaChaat.jpg",
        number: 9043246178,
    },
    {
        id: 14,
        name: "Cutlet Chana",
        image: "/images/Bakery/Chaat/Others/CutlatChanna.jpg",
        number: 9043246178,
    },
];