export const DataSavouries = [
    {
        id:1,
        name:"Mixture(s)",
        image:"/images/Bakery/Savouries/Mixture.jpg",
        desc:"7 Varieties of Mixture Available",
        number:9043246178,
        which:"bakery",
    },
    {
        id:2,
        name:"Murukku(s)",
        image:"/images/Bakery/Savouries/Murukku1.jpg",
        desc:"15 Varieties of Murukku Available",
        number:9043246178,
        which:"bakery",
    },
    {
        id:3,
        name:"Sev(s)",
        image:"/images/Bakery/Savouries/Sev2.jpg",
        desc:"05 Varieties of Sev Available",
        number:9043246178,
        which:"bakery",
    },
    {
        
        id:4,
        name:"Peanut",
        image:"/images/Bakery/Savouries/Peanut.jpg",
        desc:"05 Varieties of Peanut Available",
        number:9043246178,
        which:"bakery",
        
    },
    {
        id:5,
        name:"Pakoda",
        image:"/images/Bakery/Savouries/Pakoda.jpg",
        desc:"04 Varieties of Peanut Available",
        number:9043246178,
        which:"bakery",
    },
    {
        id:6,
        name:"Boondi",
        image:"/images/Bakery/Savouries/Boondhi.jpg",
        desc:"02 Varieties of Boondi Available",
        number:9043246178,
        which:"bakery",
    },
    {
        id:7,
        name:"Chips",
        image:"/images/Bakery/Savouries/Chips1.jpg",
        desc:"07 Varieties of Chips Available",
        number:9043246178,
        which:"bakery",
    },
    {
        id:8,
        name:"Nuts",
        image:"/images/Bakery/Savouries/Nuts.jpeg",
        desc:"07 Varieties of Nuts Available",
        number:9043246178,
        which:"bakery",
    },
    {
        id:9,
        name:"Puff (s)",
        image:"/images/Bakery/Savouries/puff1.jpg",
        desc:"Veg, Egg, Mushroom and Chicken",
        number:9043246178,
        which:"bakery",
    },
    {
        id:10,
        name:"Roasted Cashew (Munthiri)",
        image:"/images/Bakery/Savouries/Roasted-Cashew.jpg",
        desc:"Pepper and Masala Available",
        number:9043246178,
        which:"bakery",
    },
    {
        id:11,
        name:"Seedai",
        image:"/images/Bakery/Savouries/Seedai.jpg",
        desc:"Uppu, Vella and Seepu Available",
        number:9043246178,
        which:"bakery",
    },
    {
        id:13,
        name:"Navathaniyam Mixture",
        image:"/images/Bakery/Savouries/Navathaniyam.jpeg",
        number:9043246178,
        which:"bakery",
    },
    {
        id:14,
        name:"Donut",
        image:"/images/Bakery/Savouries/Donut.jpg",
        desc:"Chocolate Donut Available",
        number:9043246178,
        which:"bakery",
    },
    {
        id: 15,
        name: "Macaroon",
        image: "/images/Bakery/Savouries/Macaroon.jpg",
        number: 9043246178,
        which:"bakery",
    },
];