export const DataPani = [
    {
        id: 1,
        name: "PaniPuri",
        image: "/images/Bakery/Chaat/Panipuri/PaniPuri.jpg",
        number: 9043246178,
        which:"bakery",
    },
    {
        id: 2,
        name: "IceCream PaniPuri",
        image: "/images/Bakery/Chaat/Panipuri/IceCream.jpg",
        number: 9043246178,
        which:"bakery",
    },
    {
        id: 3,
        name: "Bhel Puri",
        image: "/images/Bakery/Chaat/Panipuri/BhelPuri.jpg",
        number: 9043246178,
        which:"bakery",
    },
    {
        id: 4,
        name: "Dahi Puri",
        image: "/images/Bakery/Chaat/Panipuri/DahiPuri.jpg",
        number: 9043246178,
        which:"bakery",
    },
    {
        id: 5,
        name: "Sev Puri",
        image: "/images/Bakery/Chaat/Panipuri/SevPuri.jpg",
        number: 9043246178,
        which:"bakery",
    },
    {
        id: 6,
        name: "Mushroom Puri",
        image: "/images/Bakery/Chaat/Panipuri/MushroomPuri.jpg",
        number: 9043246178,
        which:"bakery",
    },
    {
        id: 7,
        name: "Masala Puri",
        image: "/images/Bakery/Chaat/Panipuri/MasalaPuri.jpg",
        number: 9043246178,
        which:"bakery",
    },
    {
        id: 8,
        name: "Dahi Bhel Puri",
        image: "/images/Bakery/Chaat/Panipuri/DahiBhel.jpg",
        number: 9043246178,
        which:"bakery",
    },
    {
        id: 9,
        name: "Mix Bhel Puri",
        image: "/images/Bakery/Chaat/Panipuri/MixBhel.jpg",
        number: 9043246178,
        which:"bakery",
    },
];