export const DataSweet = [
  {
    id: 1,
    name: "Normal Sweets",
    image: "/images/Bakery/Sweets/Normal-Sweets.jpg",
    desc: "25 Varieties of Normal Sweets Available",
    number: 9043246178,
    which:"bakery",
  },
  {
    id: 2,
    name: "Ghee Sweets (Nei Sweets)",
    image: "/images/Bakery/Sweets/Ghee-Sweets.jpg",
    desc: "30 Varieties of Ghee Sweets Available",
    number: 9043246178,
    which:"bakery",
  },
  {
    id: 3,
    name: "Cashew Sweets (Munthiri)",
    image: "/images/Bakery/Sweets/Cashew-Sweets.jpg",
    desc: "10 Varieties of Cashew Sweets Available",
    number: 9043246178,
    which:"bakery",
  },
  {
    id: 4,
    name: "Halwa",
    image: "/images/Bakery/Sweets/Elaneer-Halwa.jpg",
    desc: "07 Varieties of Halwa Available. Famous Karuppati and Elaneer Halwa Available",
    number: 9043246178,
    which:"bakery",
  },
  {
    id:5,
    name:"Athirasam",
    image:"/images/Bakery/Savouries/Athirasam.jpg",
    desc:"Ghee and Yellu Available",
    number:9043246178,
    which:"bakery",
},
];
