export const DataCookie = [
    {
        id: 1,
        name: "Kambu Cookie",
        image: "/images/Bakery/Cookies/Kambu.jpg",
        number: 9043246178,
        which:"bakery",
    },
    {
        id: 2,
        name: "Badam Cookie",
        image: "/images/Bakery/Cookies/Badam.jpg",
        number: 9043246178,
        which:"bakery",
    },
    {
        id: 3,
        name: "Ragi Cookie",
        image: "/images/Bakery/Cookies/Ragi.jpg",
        number: 9043246178,
        which:"bakery",
    },
    {
        id: 4,
        name: "Oats Cookie",
        image: "/images/Bakery/Cookies/Oats.jpg",
        number: 9043246178,
        which:"bakery",
    },
    {
        id: 5,
        name: "Corn Cookie",
        image: "/images/Bakery/Cookies/Corn.jpeg",
        number: 9043246178,
        which:"bakery",
    },
    {
        id: 6,
        name: "Cashew Cookie (Munthiri)",
        image: "/images/Bakery/Cookies/Cashew.jpg",
        number: 9043246178,
        which:"bakery",
    },
    {
        id: 7,
        name: "Salt Cookie",
        image: "/images/Bakery/Cookies/Salt.jpg",
        number: 9043246178,
        which:"bakery",
    },
    {
        id: 8,
        name: "Butter Cookie",
        image: "/images/Bakery/Cookies/Butter.jpg",
        number: 9043246178,
        which:"bakery",
    },
    {
        id: 9,
        name: "Yellu Cookie(Sesame)",
        image: "/images/Bakery/Cookies/Yellu.jpg",
        number: 9043246178,
        which:"bakery",
    },
    {
        id: 10,
        name: "Peanut Cookie",
        image: "/images/Bakery/Cookies/Peanut.jpg",
        number: 9043246178,
        which:"bakery",
    },
    {
        id: 11,
        name: "Coconut Cookie",
        image: "/images/Bakery/Cookies/Coconut.jpg",
        number: 9043246178,
        which:"bakery",
    },
    {
        id: 12,
        name: "Goodday Cookie",
        image: "/images/Bakery/Cookies/Goodday.jpg",
        number: 9043246178,
        which:"bakery",
    },
    {
        id: 13,
        name: "Boost Cookie",
        image: "/images/Bakery/Cookies/Boost.jpg",
        number: 9043246178,
        which:"bakery",
    },
];