export const DataSandwich = [
    {
        id: 1,
        name: "Veg Sandwich",
        image: "/images/Bakery/Chaat/Sandwich/Veg-Sandwich.jpg",
        desc:"Available with or without cheese",
        number: 9043246178,
        which:"bakery",
    },
    {
        id: 2,
        name: "Mushroom Sandwich",
        image: "/images/Bakery/Chaat/Sandwich/Mushroom-Sandwich.jpg",
        desc:"Available with or without cheese",
        number: 9043246178,
        which:"bakery",
    },
    {
        id: 3,
        name: "Panner Sandwich",
        image: "/images/Bakery/Chaat/Sandwich/Panner-Sandwich.jpg",
        desc:"Available with or without cheese",
        number: 9043246178,
        which:"bakery",
    },
    {
        id: 4,
        name: "Masala Sandwich",
        image: "/images/Bakery/Chaat/Sandwich/Masala-Sandwich.jpg",
        number: 9043246178,
        which:"bakery",
    },
    {
        id: 5,
        name: "Egg Sandwich",
        image: "/images/Bakery/Chaat/Sandwich/Egg-Sandwich.jpg",
        number: 9043246178,
        which:"bakery",
    },
];