export const DataCake = [
    {
      id: 1,
      name: "Fresh Cream Cakes",
      image: "/images/Bakery/Cakes/Butter-Cream.jpg",
      desc: "05 Varieties of Fresh Cream Cakes Available",
      number: 9043246178,
      which:"bakery",
    },
    {
      id: 2,
      name: "Butter Cream Cakes",
      image: "/images/Bakery/Cakes/Fresh Cream Cake.jpeg",
      desc: "12 Varieties of Butter Cream Cake Available",
      number: 9043246178,
      which:"bakery",
    },
    {
      id: 3,
      name: "Dry Fruits Cakes",
      image: "/images/Bakery/Cakes/Dry-Cream.jpg",
      desc: "06 Varieties of Dry Fruits Cake Available",
      number: 9043246178,
      which:"bakery",
    },
    {
      id: 4,
      name: "Mousse Cakes",
      image: "/images/Bakery/Cakes/Mousse-Cake.jpg",
      desc: "07 Varieties of Mousse Available",
      number: 9043246178,
      which:"bakery",
    },
    {
      id: 5,
      name: "Roll Cakes",
      image: "/images/Bakery/Cakes/Roll.jpg",
      desc: "05 Varieties of Roll Cake Available",
      number: 9043246178,
      which:"bakery",
    },
    {
      id: 6,
      name: "Piece Cakes",
      image: "/images/Bakery/Cakes/Piece.jpg",
      desc: "Black and White Forest Available",
      number: 9043246178,
      which:"bakery",
    },
    {
      id: 7,
      name: "Dry Cakes",
      image: "/images/Bakery/Cakes/Dry.jpg",
      desc: "06 Varieties of Dry Cake Available",
      number: 9043246178,
      which:"bakery",
    },
    
    {
      id: 8,
      name: "Plum Cake",
      image: "/images/Bakery/Cakes/Plum-Cake.jpg",
      desc: "Christmas and New Year Available",
      number: 9043246178,
      which:"bakery",
    },
  ];
  